### ISSUE TITLE
JDK Installation not found

### ISSUE THREAD

**Issue by geezer500** [Sombody101/APKognito#1]
Trying to use APKognito...

I have jdk-23_windows-x64_bin.exe installed (from https://www.oracle.com/java/technologies/downloads/?er=221886)
However I'm still getting an error.

> 

[ERROR]   ! JDK installation found with the version 23, but it's not Java 8+
[ERROR]   ! Failed to find a valid JDK installation!
You can install the latest JDK version from here: https://www.oracle.com/java/technologies/downloads/?er=221886

What do I need to do to get APKognito to recognise the JDK (or path) ?

Thx

**Comment by Sombody101** [comment]
Seems like I have a bug in the way Java versions are checked! (Much like Phunk). The easiest way around this is to set your `JAVA_HOME` path to your JDK installation.

Press your windows key and type "Edit the system environment variables" and open the app that appears. Click the button at the bottom that says `Environment Variables`, click `New` (for either your user or the system, either should work). 

Set the variable name to `JAVA_HOME`, and the value to the path to your JDK. It should be in your Program Files. Give this path a try:
```
C:\Program Files\Java\jdk-23
```

This is what mine looks like with JDK 21 installed 
![image](https://github.com/user-attachments/assets/ac8b7d30-6deb-4f49-b145-6383553e45a6)

**Comment by Sombody101** [comment]
Hey!

Just wanted to let you know exactly how this happened because the checker was working for me. Oracle and their infinite wisdom decided to change how JDK versions are set in the Windows Registry. The new format makes it easier to check the version, but makes it more difficult to have reverse compatibility without two separate checking methods.

![image](https://github.com/user-attachments/assets/a21aeae1-1b76-47f3-8c31-713591841ea6)

**Comment by geezer500** [comment]
Hi,
Much obliged for the fix. 
It's working as expected :-) 
I'm not very experienced with enviroment paths, so rather than mess with something I don't know about, I thought I would ask!
Thanks for help and of course the app..
