### ISSUE TITLE
Directory not found exception

### ISSUE THREAD

**Issue by TreverK** [Sombody101/APKognito#4]
Error occurs after selecting any apk

[logpack.zip](https://github.com/user-attachments/files/17552857/logpack.zip)
![Unhandled Exception 10_29_2024 12_00_32 AM](https://github.com/user-attachments/assets/4349ec47-8c87-4ee8-b72f-c82de6ca897b)
![Unhandled Exception 10_29_2024 12_00_40 AM](https://github.com/user-attachments/assets/76ba9f3a-2a07-405e-9947-8a8aa5370032)

Win 11
Chrome
APKognito-1.6.9059.27184

**Comment by Sombody101** [comment]
I've created a new release with a fix.
[v1.6.9068.27333](https://github.com/Sombody101/APKognito/releases/tag/v1.6.9068.27333)

The exception was due to some code that calculates OBB file sizes assuming the directory exists. I also fixed the auto update service so APKognito will actually update when you tell it to. I also added a button that cancels the update and turns off Auto Updates on the dialog box that asks to update.

Let me know if you have other issues or if this didn't work!

**Comment by TreverK** [comment]
I just tried it with a couple different apk and I'm getting a new error
![APKognito 10_29_2024 5_38_50 PM](https://github.com/user-attachments/assets/59140750-0695-4dd0-ba2e-8497b2360052)

**Comment by Sombody101** [comment]
Can you attach your applog.log file again? It will let me know where the exception occurred.

**Comment by TreverK** [comment]
Sorry I forgot to include it.
[logpack.zip](https://github.com/user-attachments/files/17566559/logpack.zip)

**Comment by Sombody101** [comment]
This is going to sound like a bit of an odd request, but can you attach the file at `%LOCALAPPDATA%\Temp\APKognito-1ilcy4ai.42j\com.stremio.one-1.6.12-11049190-armeabi-v7a_2024-10-29_17-46-33\smali\com\apkognito1\core\Core$EventListener.smali` if you still have it?

**Comment by TreverK** [comment]
I cannot find it even after attempting to rename the APK again.

**Comment by Sombody101** [comment]
I've created a new release with a fix.
[v1.6.9069.21655](https://github.com/Sombody101/APKognito/releases/tag/v1.6.9069.21655)

The issue was with how the company name was extracted from the full package name. It was getting the app name, leading to a `DirectoryNotFoundException`.

Let me know if you run into more errors!

**Comment by TreverK** [comment]
I just gave it a try with the newest version and I'm still getting an error.
[logpack.zip](https://github.com/user-attachments/files/17581376/logpack.zip)

**Comment by Sombody101** [comment]
I've made a change that will provide more information for debugging as the current logfile isn't.
Sorry for adding more delay.

[v1.6.9070.14089](https://github.com/Sombody101/APKognito/releases/tag/v1.6.9070.14089)

**Comment by TreverK** [comment]
Ok no problem. Thank for you help. I tried two APKs, one was successful and the other has an error.
[logpack.zip](https://github.com/user-attachments/files/17594220/logpack.zip)
